import type { LucideIcon } from 'lucide-react';
import {
  Beer,
  Brush,
  Bug,
  Car,
  Coffee,
  Droplets,
  Egg,
  Flame,
  Flower2,
  GlassWater,
  Leaf,
  Paintbrush,
  PenLine,
  Pill,
  Pipette,
  Shirt,
  Sparkles,
  Sun,
  TreePine,
  UtensilsCrossed,
  Wine,
  Wrench,
} from 'lucide-react';
import type { StainIconKind } from '@/data/laundry-stains';

export const stainIconMap: Record<StainIconKind, LucideIcon> = {
  coffee: Coffee,
  tea: GlassWater,
  wine: Wine,
  blood: Droplets,
  chocolate: UtensilsCrossed,
  oil: Flame,
  grease: Flame,
  ink: PenLine,
  marker: PenLine,
  lipstick: Sparkles,
  makeup: Brush,
  perfume: Pipette,
  mud: TreePine,
  grass: Leaf,
  sweat: Shirt,
  milk: GlassWater,
  juice: GlassWater,
  cola: GlassWater,
  rust: Wrench,
  wax: Sparkles,
  paint: Paintbrush,
  glue: Pipette,
  tar: Car,
  gum: Sparkles,
  smoke: Flame,
  mold: Bug,
  butter: UtensilsCrossed,
  ketchup: UtensilsCrossed,
  sauce: UtensilsCrossed,
  mustard: UtensilsCrossed,
  soy: UtensilsCrossed,
  curry: UtensilsCrossed,
  medicine: Pill,
  engine: Car,
  dye: Paintbrush,
  egg: Egg,
  beer: Beer,
  honey: UtensilsCrossed,
  sunscreen: Sun,
  polish: Sparkles,
  pollen: Flower2,
  soot: Flame,
  berry: UtensilsCrossed,
  turmeric: UtensilsCrossed,
  vomit: Droplets,
  bleach: Droplets,
  fuel: Car,
  detergent: Droplets,
  avocado: UtensilsCrossed,
  caramel: UtensilsCrossed,
  cocoa: Coffee,
  iodine: Pill,
  deodorant: Pipette,
  hairDye: Brush,
  foundation: Brush,
  charcoal: Flame,
  sap: TreePine,
  iceCream: UtensilsCrossed,
  whiskey: Wine,
  champagne: Wine,
  mayonnaise: UtensilsCrossed,
  saladDressing: UtensilsCrossed,
  foodOil: Flame,
};

export function getStainIcon(kind: StainIconKind): LucideIcon {
  return stainIconMap[kind] ?? Droplets;
}
