export const STORAGE_KEYS = {
  employees: 'tpl-employees-v1',
  shifts: 'tpl-shifts',
  leaves: 'tpl-leaves-v1',
  priceList: 'tpl-price-list-v2',
  fabrics: 'tpl-fabrics-v1',
  chemicals: 'tpl-chemicals-v2',
  programs: 'tpl-programs-v2',
  stains: 'tpl-stains-v1',
  careSymbols: 'tpl-care-symbols-v1',
  homeContent: 'tpl-home-content-v1',
  training: 'tpl-training',
  aiSettings: 'tpl-ai-settings-v1',
  inventory: 'tpl-inventory-v3',
  inventoryPlan: 'tpl-inventory-plan-v1',
  inventoryLegacy: 'tpl-inventory-v2',
  inventoryArchives: 'tpl-inventory-archives-v1',
  inventoryArchivesMeta: 'tpl-inventory-archives-meta',
  authSession: 'tpl-auth-session',
  authUsers: 'tpl-auth-users',
  auditLog: 'tpl-audit-log',
  fabricFavorites: 'tpl-fabric-favorites',
  fabricRecent: 'tpl-fabric-recent',
  theme: 'tpl-theme',
  language: 'tpl-language',
  priceListLegacy: 'tpl-price-list',
} as const;

export const DATA_STORE_KEYS = [
  STORAGE_KEYS.employees,
  STORAGE_KEYS.shifts,
  STORAGE_KEYS.leaves,
  STORAGE_KEYS.priceList,
  STORAGE_KEYS.fabrics,
  STORAGE_KEYS.chemicals,
  STORAGE_KEYS.programs,
  STORAGE_KEYS.stains,
  STORAGE_KEYS.careSymbols,
  STORAGE_KEYS.homeContent,
  STORAGE_KEYS.training,
  STORAGE_KEYS.aiSettings,
  STORAGE_KEYS.inventory,
] as const;
